version: "3"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    image: backend:production
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    entrypoint: /home/app/backend/entrypoints/production.sh
    environment:
      - DJANGO_READ_DOT_ENV_FILE=true
      - DJANGO_DOT_ENV_FILES=.env.production
    volumes:
      - static_volume:/home/app/backend/staticfiles
    depends_on:
      - postgres
    expose:
      - 8000

  frontend:
    image: frontend:production
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - APP_ENV=production
        - NODE_ENV=production
    ports:
      - 3000:3000
    expose:
      - 3000

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/home/app/backend/staticfiles
    ports:
      - 1337:80
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
