# Generated by Django 3.2.10 on 2022-02-04 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'verbose_name_plural': 'Project Categories'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name_plural': 'Work'},
        ),
    ]
