# Generated by Django 3.2.10 on 2022-02-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20220118_2222'),
        ('projects', '0002_alter_projectmember_allocated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(through='projects.ProjectMember', to='members.Member'),
        ),
    ]
