# Generated by Django 3.2.10 on 2022-02-06 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20220118_2222'),
        ('projects', '0003_alter_project_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.member'),
        ),
    ]
