# Generated by Django 3.2.10 on 2022-02-12 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_alter_work_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmember",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="project_members", to="projects.project"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Pending"), (2, "Approved"), (3, "Disapproved"), (4, "Inactive")], default=1
            ),
        ),
    ]
