# Generated by Django 3.2.12 on 2022-04-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0002_auto_20220408_2256"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="product_category",
            new_name="product_categories",
        ),
    ]
