# Generated by Django 3.2.10 on 2022-02-11 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_alter_member_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30)),
                ("work_hours", models.IntegerField(default=18)),
                ("shift_count", models.IntegerField(default=4)),
            ],
        ),
        migrations.AddField(
            model_name="member",
            name="role",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="members.role"
            ),
        ),
    ]
