# Generated by Django 3.2.10 on 2022-03-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='name',
        ),
        migrations.RemoveField(
            model_name='role',
            name='shift_count',
        ),
        migrations.RemoveField(
            model_name='role',
            name='work_hours',
        ),
        migrations.AddField(
            model_name='role',
            name='type',
            field=models.CharField(choices=[('FULL_RECEPTION', 'Full vakt'), ('FULL_WORK', 'Full regi'), ('HYBRID', 'Hybrid'), ('ADMIN', 'Utvalget')], default='HYBRID', max_length=30),
        ),
    ]
