# Generated by Django 3.2.10 on 2022-03-05 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shift",
            name="date",
        ),
        migrations.RemoveField(
            model_name="shift",
            name="semester",
        ),
        migrations.CreateModel(
            name="ShiftDate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("semester", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reception.semester")),
            ],
        ),
        migrations.AddField(
            model_name="shift",
            name="shift_date",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shifts",
                to="reception.shiftdate",
            ),
        ),
    ]
